import type {NextPage} from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import {Box, Divider} from "@mui/material";
import CollectionList from "../components/collectionList";

const Home: NextPage = () => {
  return (
    <Box className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <Box
          sx={{
            width: '100%',
            height: 300,
            backgroundColor: 'primary.dark',
            '&:hover': {
              backgroundColor: 'primary.main',
              opacity: [0.9, 0.8, 0.7],
            },
          }}
        >
          <div>민팅 페이지로</div>
        </Box>
        <Box sx={{
          width: '100%',
          height: 10,
        }}></Box>
        <h4>New</h4>
        <Divider variant="middle"/>
        <CollectionList/>
      </main>
    </Box>
  )
}

export default Home
