import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import ItemList from "../components/itemList";
import {Box, Divider, Typography} from "@mui/material";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <Box
              sx={{
                  width: '100%',
                  height: 300,
                  backgroundColor: 'primary.dark',
                  '&:hover': {
                      backgroundColor: 'primary.main',
                      opacity: [0.9, 0.8, 0.7],
                  },
              }}
          >
              <Typography>민팅 페이지로</Typography>
          </Box>
          <Box  sx={{
              width: '100%',
              height: 10,
          }}></Box>
          <Typography gutterBottom variant="h4" component="div">
              New
          </Typography>
          <Divider variant="middle" />
          <ItemList/>
      </main>
    </div>
  )
}

export default Home
