import type {NextPage} from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import {Box, Divider} from "@mui/material";
import CollectionList from "../components/collectionList";
import {useEffect, useState} from "react";
import {getRandomColor} from "../utils/common";

const Home: NextPage = () => {
  const [bgColor, setBGColor] = useState('')

  useEffect(() => {
    setBGColor(getRandomColor())
  }, [])

  return (
    <Box className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <Box sx={{height: "300px", padding: "20px", backgroundColor: `${bgColor}`, color: "#fff", position: 'relative'}}>
          <Box>민팅 페이지로</Box>
        </Box>
        <Box sx={{
          width: '100%',
          height: 10,
        }}></Box>

        <Box sx={{ width : '90%', margin: '0 auto'}}>
          <h4>New collections</h4>
          <Divider variant="middle"/>
          <CollectionList/>
        </Box>
      </main>
    </Box>
  )
}

export default Home
